# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZmY2MTE1OTUwNzM0Nzc4NDQ4YjIyOTMxOGZlOTJiNzkyN2M5Mzc5ZWFiMmU1ZjZlMTgzNTQ1NmViZjU2YWI3OTE4ZGVlN2JlNTk1ZWY3ODM2ODczYzlkN2YxYTNkN2U4MGMwMDg1MWUyNTg5ZDIwMWI5NjJjYzU1ZjU4NTgwMmQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
